[tool.black]
line-length = 80
target-version = ['py36', 'py37']

[tool.pylint.messages_control]
disable = [
    "wrong-hanging-indentation",  # C0330
    "bad-whitespace",  # C0326
    "duplicate-code"  # R0801
    # "no-name-in-module"
]

[tool.pylint.format]
max-line-length = "80"
