name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check Ubuntu version we are running under
      run: |
        uname -a
    - name: Current environment
      run: |
        env
    - name: Install DLite
      run: |
        emmodir=$PWD
        #sudo apt-get install gcc
        #sudo apt-get install make
        #sudo apt-get install cmake
        #sudo apt-get install libjansson-dev
        #sudo apt-get install libhdf5-dev
        #sudo apt-get install python-dev
        #sudo apt-get install swig3.0
        #sudo apt-get install doxygen
        #pip install numpy
        #cd ..
        #git clone https://github.com/SINTEF/dlite.git
        #cd dlite
        #git submodule init
        #git submodule update
        #mkdir build
        #cd build
        #cmake ..
        #make
        #make test
        #sudo make install
        #cd $emmodir
        #pwd
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-line-length=79 --statistics
    - name: Install pandoc 2.1.2
      run: |
        #sudo apt-get install pandoc
        wget https://github.com/jgm/pandoc/releases/download/2.1.2/pandoc-2.1.2-1-amd64.deb
        sudo apt-get install ./pandoc-2.1.2-1-amd64.deb
    - name: Install other dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install graphviz
        sudo apt-get install texlive-xetex
        sudo apt-get install texlive-latex-extra
    - name: Install EMMO-python
      run: |
        python setup.py install
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Create EMMO documentation
      run: |
        cd examples/emmodoc
        python ../../tools/ontodoc -f simple-html emmo-inferred.owl emmo-simple.html
        python ../../tools/ontodoc -t emmo.md emmo-inferred.owl emmo.html
        python ../../tools/ontodoc -t emmo.md emmo-inferred.owl emmo.pdf
        cd -
    - name: Run vertical demo
      run: |
        cd demo/vertical
        python define_ontology.py
        python plot_ontology.py
        cd -
    - name: Run horizontal demo
      run: |
        cd demo/horizontal
        #python step1_generate_metadata.py
        #python step2_define_metadata.py
        #python step3_instantiate.py
        #python step4_map_instance.py
        cd -
